from importlib import import_module
from typing import TYPE_CHECKING

from ._sqlite import (
    SQLiteJournalCapabilities,
    SQLiteJournalModeError,
    sqlite_journal_capabilities,
    sqlite_wal_is_safe,
)
from .action_contracts import ActionContract, BoundAction
from .approval_store import (
    ApprovalReservation,
    ApprovalStatus,
    ApprovalStore,
    InMemoryApprovalStore,
    SQLiteApprovalStore,
    StoredApproval,
)
from .audit import AuditSink, InMemoryAuditSink, JSONLAuditSink, SQLiteAuditSink
from .context import (
    ExecutionContext,
    ExecutionMode,
    ExecutionStatus,
    HistoryEntry,
    RiskTier,
    ToolCall,
)
from .debugger import DiffEntry, ReplayDebugger, diff_values
from .decision_explanations import (
    DECISION_EXPLANATION_ATTACHMENT_SCHEMA_V1,
    DecisionControl,
    DecisionExplanationAttachment,
    DecisionExplanationValidationError,
    controls_from_context,
)
from .decisions import (
    ApprovalRequest,
    DecisionOutcome,
    DecisionProvider,
    DecisionRecord,
    HumanDecisionProvider,
)
from .errors import (
    AuditDeliveryError,
    AuditIntegrityError,
    ContextMutationError,
    ContractValidationError,
    GovernanceCancelledError,
    GovernanceDenied,
    GovernanceError,
    ReconciliationAuditDeliveryPendingError,
    RegistryError,
    ToolExecutionError,
    get_cancellation_context,
)
from .evaluation import (
    DriftRecord,
    EvaluationSuite,
    PolicyDriftDetector,
    PolicyDriftReport,
    RegressionCase,
    RegressionReport,
    RegressionResult,
)
from .evidence import (
    EVIDENCE_BUNDLE_SCHEMA_V1,
    AuditAnchor,
    EvidenceBundle,
    EvidenceBundleValidationError,
    EvidenceExecution,
    ReconciliationEvidenceEntry,
)
from .evidence_external import (
    ANCHOR_PROVIDER_ENTRY_POINT_GROUP,
    RECEIPT_VERIFIER_ENTRY_POINT_GROUP,
    AnchorProvider,
    AnchorSequenceEntry,
    AnchorVerificationRequest,
    AnchorVerificationResult,
    EvidenceExternalValidationError,
    InMemoryAnchorProvider,
    InMemoryReceiptVerifier,
    ReceiptAttachment,
    ReceiptVerificationExpectation,
    ReceiptVerificationRequest,
    ReceiptVerificationResult,
    ReceiptVerifier,
    UnsupportedReceiptVerifier,
)
from .evidence_signing import (
    EVIDENCE_SIGNATURE_ATTACHMENT_SCHEMA_V1,
    EVIDENCE_TRUST_ROOTS_SCHEMA_V1,
    Ed25519EvidenceSigner,
    EvidenceSignatureAttachment,
    EvidenceSignatureValidationError,
    EvidenceSignatureVerificationError,
    EvidenceSigner,
    EvidenceSigningDependencyError,
    EvidenceSigningError,
    EvidenceTrustRoot,
    EvidenceTrustRoots,
    EvidenceTrustRootValidationError,
    sign_evidence_bundle,
    verify_evidence_bundle_signature,
)
from .hooks import HookPoint, HookRegistry
from .identity import (
    HMACClaimsIdentityProvider,
    IdentityProvider,
    IdentityReplayStore,
    InMemoryIdentityReplayStore,
    SQLiteIdentityReplayStore,
    StaticIdentityProvider,
    VerifiedPrincipal,
)
from .middleware import (
    ApprovalMiddleware,
    AuditMiddleware,
    DecisionMiddleware,
    ExecutionMiddleware,
    GatingMiddleware,
    InMemoryMetrics,
    LLMMiddleware,
    MetricsMiddleware,
    MetricsSnapshot,
    Middleware,
    MiddlewareKind,
    MiddlewareMetadata,
    ObservingMiddleware,
    RetryMiddleware,
    Rule,
    RuleMiddleware,
    SemanticReview,
    TimeoutMiddleware,
)
from .pipeline import Pipeline
from .plugins import (
    OPAClient,
    OPADecision,
    OPAMiddleware,
    OPAPlugin,
    Plugin,
    PluginManager,
    PrometheusMiddleware,
    PrometheusPlugin,
    RegisteredPlugin,
    RuntimeBuilder,
    SlackNotificationMiddleware,
    SlackPlugin,
    SlackWebhookNotifier,
)
from .policy import PolicyMiddleware, SimplePolicy
from .production import (
    IdentityDigestKeyProvider,
    PreconditionDigestProvider,
    ProductionProfile,
    ProductionReadinessError,
    ProductionReadinessReason,
    ProductionReadinessReport,
    ProductionReadinessState,
    ToolProductionReadiness,
)
from .reconciliation import (
    InMemoryReconciliationLedger,
    InvalidReconciliationTransitionError,
    ManualResolution,
    ProviderDescriptor,
    ReconciliationAttemptContext,
    ReconciliationAttemptOutcome,
    ReconciliationAuditEnvelope,
    ReconciliationConflictError,
    ReconciliationDisposition,
    ReconciliationError,
    ReconciliationEventKind,
    ReconciliationFinding,
    ReconciliationHead,
    ReconciliationLedger,
    ReconciliationNotFoundError,
    ReconciliationProvider,
    ReconciliationRecord,
    ReconciliationState,
    ReconciliationTransition,
    ReconciliationTransitionSource,
    ReconciliationValidationError,
    SQLiteReconciliationLedger,
    UnknownAction,
    idempotency_namespace_digest,
    new_execution_record_id,
    tenant_partition_digest,
)
from .registry import (
    IdempotencyAlreadyAppliedError,
    IdempotencyClaim,
    IdempotencyConflictError,
    IdempotencyInProgressError,
    IdempotencyOutcomeUnknownError,
    IdempotencyStore,
    InMemoryIdempotencyStore,
    SQLiteIdempotencyStore,
    ToolSpec,
)
from .replay import ReplayTrace
from .resilience import (
    CapacityExceededError,
    CircuitBreaker,
    CircuitOpenError,
    CircuitState,
    RuntimeLimits,
    StageTimeoutError,
)
from .runtime import Harness, InvocationOptions, RunResult, Runtime
from .runtime_events import (
    RUNTIME_EVENT_SCHEMA_V1,
    RuntimeEvent,
    RuntimeEventAction,
    RuntimeEventStream,
    RuntimeEventSubscriber,
    RuntimeEventSubscription,
)
from .snapshots import (
    ContextSnapshot,
    InMemorySnapshotStore,
    JSONLSnapshotStore,
    SnapshotMiddleware,
    SnapshotStore,
    SQLiteSnapshotStore,
)
from .telemetry import OpenTelemetryMiddleware
from .visualization import trace_to_mermaid
from .yaml_policy import PolicyDocument, PolicyValidationError, YAMLPolicyLoader

if TYPE_CHECKING:
    from .verify import (
        DecisionExplanationComparison,
        DecisionExplanationDifference,
        DecisionExplanationVerificationError,
        VerifiedDecisionExplanation,
        compare_verified_decision_explanations,
        verify_decision_explanation,
        verify_decision_explanation_document,
    )

__version__ = "0.9.1"

_LAZY_VERIFY_EXPORTS = frozenset(
    {
        "DecisionExplanationComparison",
        "DecisionExplanationDifference",
        "DecisionExplanationVerificationError",
        "VerifiedDecisionExplanation",
        "compare_verified_decision_explanations",
        "verify_decision_explanation",
        "verify_decision_explanation_document",
    }
)


def __getattr__(name: str) -> object:
    """Load verification exports without preloading the verifier CLI module."""
    if name not in _LAZY_VERIFY_EXPORTS:
        raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
    value = getattr(import_module(".verify", __name__), name)
    globals()[name] = value
    return value

__all__ = [
    "ActionContract",
    "ApprovalMiddleware",
    "ApprovalRequest",
    "ApprovalReservation",
    "ApprovalStatus",
    "ApprovalStore",
    "ANCHOR_PROVIDER_ENTRY_POINT_GROUP",
    "AnchorProvider",
    "AnchorSequenceEntry",
    "AnchorVerificationRequest",
    "AnchorVerificationResult",
    "AuditDeliveryError",
    "AuditAnchor",
    "AuditSink",
    "AuditIntegrityError",
    "AuditMiddleware",
    "BoundAction",
    "ContextMutationError",
    "ContextSnapshot",
    "ContractValidationError",
    "CapacityExceededError",
    "CircuitBreaker",
    "CircuitOpenError",
    "CircuitState",
    "DecisionMiddleware",
    "DecisionControl",
    "DecisionExplanationAttachment",
    "DecisionExplanationComparison",
    "DecisionExplanationDifference",
    "DecisionExplanationValidationError",
    "DecisionExplanationVerificationError",
    "DecisionOutcome",
    "DecisionProvider",
    "DecisionRecord",
    "DiffEntry",
    "DriftRecord",
    "ExecutionMiddleware",
    "ExecutionContext",
    "ExecutionMode",
    "ExecutionStatus",
    "EVIDENCE_BUNDLE_SCHEMA_V1",
    "DECISION_EXPLANATION_ATTACHMENT_SCHEMA_V1",
    "EVIDENCE_SIGNATURE_ATTACHMENT_SCHEMA_V1",
    "EVIDENCE_TRUST_ROOTS_SCHEMA_V1",
    "Ed25519EvidenceSigner",
    "EvidenceBundle",
    "EvidenceBundleValidationError",
    "EvidenceExternalValidationError",
    "EvidenceExecution",
    "EvidenceSignatureAttachment",
    "EvidenceSignatureValidationError",
    "EvidenceSignatureVerificationError",
    "EvidenceSigner",
    "EvidenceSigningDependencyError",
    "EvidenceSigningError",
    "EvidenceTrustRoot",
    "EvidenceTrustRootValidationError",
    "EvidenceTrustRoots",
    "EvaluationSuite",
    "GatingMiddleware",
    "GovernanceDenied",
    "GovernanceCancelledError",
    "GovernanceError",
    "get_cancellation_context",
    "Harness",
    "HistoryEntry",
    "HookPoint",
    "HookRegistry",
    "HumanDecisionProvider",
    "HMACClaimsIdentityProvider",
    "IdentityProvider",
    "IdentityDigestKeyProvider",
    "IdentityReplayStore",
    "PreconditionDigestProvider",
    "InMemoryAuditSink",
    "InMemoryAnchorProvider",
    "InMemoryApprovalStore",
    "InMemoryIdentityReplayStore",
    "InMemoryIdempotencyStore",
    "InMemoryReconciliationLedger",
    "InMemoryReceiptVerifier",
    "InMemoryMetrics",
    "InMemorySnapshotStore",
    "InvocationOptions",
    "InvalidReconciliationTransitionError",
    "JSONLAuditSink",
    "JSONLSnapshotStore",
    "LLMMiddleware",
    "ManualResolution",
    "Middleware",
    "MiddlewareKind",
    "MiddlewareMetadata",
    "MetricsMiddleware",
    "MetricsSnapshot",
    "ObservingMiddleware",
    "OpenTelemetryMiddleware",
    "OPAClient",
    "OPADecision",
    "OPAMiddleware",
    "OPAPlugin",
    "Pipeline",
    "Plugin",
    "PluginManager",
    "PolicyDocument",
    "PolicyDriftDetector",
    "PolicyDriftReport",
    "PolicyMiddleware",
    "PolicyValidationError",
    "ProductionProfile",
    "ProductionReadinessError",
    "ProductionReadinessReason",
    "ProductionReadinessReport",
    "ProductionReadinessState",
    "ProviderDescriptor",
    "PrometheusMiddleware",
    "PrometheusPlugin",
    "RegisteredPlugin",
    "RegistryError",
    "ReconciliationAuditDeliveryPendingError",
    "ReconciliationAttemptContext",
    "ReconciliationAttemptOutcome",
    "ReconciliationAuditEnvelope",
    "ReconciliationConflictError",
    "ReconciliationDisposition",
    "ReconciliationError",
    "ReconciliationEvidenceEntry",
    "ReconciliationEventKind",
    "ReconciliationFinding",
    "ReconciliationHead",
    "ReconciliationLedger",
    "ReconciliationNotFoundError",
    "ReconciliationProvider",
    "ReconciliationRecord",
    "ReconciliationState",
    "ReconciliationTransition",
    "ReconciliationTransitionSource",
    "ReconciliationValidationError",
    "RECEIPT_VERIFIER_ENTRY_POINT_GROUP",
    "ReceiptAttachment",
    "ReceiptVerifier",
    "ReceiptVerificationExpectation",
    "ReceiptVerificationRequest",
    "ReceiptVerificationResult",
    "ReplayTrace",
    "ReplayDebugger",
    "RegressionCase",
    "RegressionReport",
    "RegressionResult",
    "RiskTier",
    "Rule",
    "RuleMiddleware",
    "RetryMiddleware",
    "RunResult",
    "Runtime",
    "RuntimeEvent",
    "RuntimeEventAction",
    "RuntimeEventStream",
    "RuntimeEventSubscriber",
    "RuntimeEventSubscription",
    "RuntimeBuilder",
    "RuntimeLimits",
    "RUNTIME_EVENT_SCHEMA_V1",
    "SemanticReview",
    "SimplePolicy",
    "SnapshotMiddleware",
    "SnapshotStore",
    "SQLiteApprovalStore",
    "SQLiteAuditSink",
    "SQLiteIdentityReplayStore",
    "SQLiteIdempotencyStore",
    "SQLiteJournalCapabilities",
    "SQLiteJournalModeError",
    "SQLiteReconciliationLedger",
    "SQLiteSnapshotStore",
    "StageTimeoutError",
    "StaticIdentityProvider",
    "StoredApproval",
    "SlackNotificationMiddleware",
    "SlackPlugin",
    "SlackWebhookNotifier",
    "TimeoutMiddleware",
    "ToolCall",
    "ToolSpec",
    "ToolProductionReadiness",
    "ToolExecutionError",
    "UnknownAction",
    "UnsupportedReceiptVerifier",
    "VerifiedDecisionExplanation",
    "VerifiedPrincipal",
    "YAMLPolicyLoader",
    "diff_values",
    "compare_verified_decision_explanations",
    "controls_from_context",
    "trace_to_mermaid",
    "IdempotencyConflictError",
    "IdempotencyAlreadyAppliedError",
    "IdempotencyClaim",
    "IdempotencyInProgressError",
    "IdempotencyOutcomeUnknownError",
    "IdempotencyStore",
    "idempotency_namespace_digest",
    "new_execution_record_id",
    "tenant_partition_digest",
    "verify_decision_explanation",
    "verify_decision_explanation_document",
    "sqlite_journal_capabilities",
    "sqlite_wal_is_safe",
    "sign_evidence_bundle",
    "verify_evidence_bundle_signature",
]
